export const products = [
    {
      id: 1,
      name: 'อกไก่สด',
      caption: 'โปรตีนสูง',
      category: 'Raw',
      price: 85,
      inStock: true,
      image: '/images/อกไก่สด.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 2,
      name: 'หมูสับ',
      caption: 'เหมาะกับเมนูผัด',
      category: 'Raw',
      price: 75,
      inStock: false,
      image: '/images/หมูสับ.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 3,
      name: 'ผักกาดขาว',
      caption: 'สดใหม่จากสวน',
      category: 'Vegetable',
      price: 25,
      inStock: true,
      image: '/images/ผักกาดขาว.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 4,
      name: 'มะม่วง',
      caption: 'หวานอมเปรี้ยว',
      category: 'Fruit',
      price: 40,
      inStock: true,
      image: '/images/มะม่วง.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 5,
      name: 'ซอสหอยนางรม',
      caption: 'เพิ่มรสชาติกลมกล่อม',
      category: 'Seasoning',
      price: 55,
      inStock: true,
      image: '/images/ซอสหอยนางรม.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 6,
      name: 'ข้าวไข่เจียวพร้อมทาน',
      caption: 'อุ่นไมโครเวฟได้ทันที',
      category: 'RTE Food',
      price: 60,
      inStock: true,
      image: '/images/ข้าวไข่เจียว.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 7,
      name: 'แตงกวา',
      caption: 'สดกรอบนาน',
      category: 'Vegetable',
      price: 20,
      inStock: true,
      image: '/images/แตงกวา.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 8,
      name: 'ไข่ไก่เบอร์ 1',
      caption: 'ฟาร์มออร์แกนิก',
      category: 'Raw',
      price: 45,
      inStock: true,
      image: '/images/ไข่ไก่.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 9,
      name: 'แครอท',
      caption: 'หวานธรรมชาติ',
      category: 'Vegetable',
      price: 18,
      inStock: false,
      image: '/images/แครอท.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 10,
      name: 'ข้าวผัดแช่แข็ง',
      caption: 'พร้อมทานใน 5 นาที',
      category: 'RTE Food',
      price: 50,
      inStock: true,
      image: '/images/ข้าวผัด.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 11,
      name: 'พริกไทยดำป่น',
      caption: 'เผ็ดหอมกำลังดี',
      category: 'Seasoning',
      price: 30,
      inStock: true,
      image: '/images/พริกไทย.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 12,
      name: 'หน่อไม้ฝรั่ง',
      caption: 'ผักสุขภาพ',
      category: 'Vegetable',
      price: 32,
      inStock: false,
      image: '/images/หน่อไม้.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 13,
      name: 'กล้วยหอม',
      caption: 'หอมหวานอร่อย',
      category: 'Fruit',
      price: 22,
      inStock: true,
      image: '/images/กล้วย.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 14,
      name: 'น้ำมันพืช',
      caption: 'สำหรับผัดและทอด',
      category: 'Seasoning',
      price: 45,
      inStock: true,
      image: '/images/น้ำมัน.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 15,
      name: 'สเต็กหมูหมัก',
      caption: 'พร้อมปรุง',
      category: 'Raw',
      price: 120,
      inStock: true,
      image: '/images/สเต็กหมู.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 16,
      name: 'ข้าวมันไก่พร้อมทาน',
      caption: 'สะดวกทุกมื้อ',
      category: 'RTE Food',
      price: 70,
      inStock: true,
      image: '/images/ข้าวมันไก่.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 17,
      name: 'สับปะรด',
      caption: 'หวานฉ่ำ',
      category: 'Fruit',
      price: 28,
      inStock: false,
      image: '/images/สับปะรด.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 18,
      name: 'พริกแกงเขียวหวาน',
      caption: 'รสจัดถึงเครื่อง',
      category: 'Seasoning',
      price: 25,
      inStock: true,
      image: '/images/พริกแกง.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 19,
      name: 'ไข่ต้มพร้อมทาน',
      caption: 'ปอกเปลือกแล้ว',
      category: 'RTE Food',
      price: 35,
      inStock: true,
      image: '/images/ไข่ต้ม.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 20,
      name: 'กะหล่ำปลี',
      caption: 'กรอบ หวาน',
      category: 'Vegetable',
      price: 17,
      inStock: true,
      image: '/images/กะหล่ำ.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 21,
      name: 'ข้าวเหนียวหมูปิ้ง',
      caption: 'อุ่นร้อนอร่อย',
      category: 'RTE Food',
      price: 65,
      inStock: true,
      image: '/images/หมูปิ้ง.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 22,
      name: 'ซอสพริก',
      caption: 'เผ็ดจี๊ดจ๊าด',
      category: 'Seasoning',
      price: 18,
      inStock: false,
      image: '/images/ซอสพริก.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 23,
      name: 'กุ้งสด',
      caption: 'ทะเลแท้ๆ',
      category: 'Raw',
      price: 150,
      inStock: true,
      image: '/images/กุ้งสด.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 24,
      name: 'ข้าวโพดหวาน',
      caption: 'ต้มพร้อมทาน',
      category: 'Vegetable',
      price: 26,
      inStock: true,
      image: '/images/ข้าวโพด.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 25,
      name: 'ลำไย',
      caption: 'ลูกโต หอม',
      category: 'Fruit',
      price: 35,
      inStock: false,
      image: '/images/ลำไย.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 26,
      name: 'มะเขือเทศ',
      caption: 'ปลอดสาร',
      category: 'Vegetable',
      price: 22,
      inStock: true,
      image: '/images/มะเขือเทศ.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 27,
      name: 'แซนวิชแฮมชีส',
      caption: 'เช้าสะดวก',
      category: 'RTE Food',
      price: 40,
      inStock: true,
      image: '/images/แซนวิช.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 28,
      name: 'ซอสถั่วเหลือง',
      caption: 'หมักนาน',
      category: 'Seasoning',
      price: 28,
      inStock: true,
      image: '/images/ซอสถั่ว.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 29,
      name: 'ส้ม',
      caption: 'หวานอมเปรี้ยว',
      category: 'Fruit',
      price: 30,
      inStock: true,
      image: '/images/ส้ม.jpeg',
      exp: '31/12/2025',
    },
    {
      id: 30,
      name: 'เนื้อวัวสไลซ์',
      caption: 'ทำชาบูได้',
      category: 'Raw',
      price: 180,
      inStock: false,
      image: '/images/เนื้อวัว.jpeg',
      exp: '31/12/2025',
    }
  ];