# Generated by Django 5.0.4 on 2025-05-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'ตะกร้า'), ('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('processing', 'กำลังเตรียมของ'), ('in_transit', 'กำลังจัดส่ง'), ('shipped', 'จัดส่งแล้ว')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order_management.order'),
        ),
    ]
