# Generated by Django 5.0.4 on 2025-05-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_remove_order_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_payment_method_id',
        ),
    ]
